# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "lXCOk1ln7I9XORrAylxeeWWmfAqJL1IWIMXYfbJUd2u5PRA+YpMs3/XcGPozRl/xiy6KrOJY69rBRWvn5ZssbRtdEkhHV5fA/EdkQ0dlGYmRR6QMv+bhx56ld6f0ecaAtsMn9RMfcA2a+47pTwAlfVHcNs/LaPByCLW768PB2wp6KtEaAtjuEzmUPQw/3cB/24bR+D1NQqmFOAD3ntYqtiF3BWtexHLKBGh/Nx6vbE1RV3f+LdEM+ahYSVxgGSPVEy/yTobaoqfGE+IyjlxkRvNpbAnx+bXSxbmJDdP8U5iPNJZeZPnjZ9vmiY26VEGHqeMv53Zs/ZWXRrGAsXjE4TF9CRm2zwJ+eIyFHJpfkDmGSW2P3qWMSMqeLbsj2Fp6sgTpyqKssHdxSq0UamOMkTeeIbpj2jEqzyCO2JnqDsktbjERDBrddfTw6uMA2AtIn5xGtoYA6FSMsiVmHqMUJnrvGy17RpmFEHCo5B3qDfdkPlnA5/OJO9EdFrf+wfB/s9fClIarrVcrjq96EgcIKdqSXm6DWM+VpU13IIhF9+6ykv2gowiIXs4NLvvgKsGebOSjHjYekU6d/iXJ4emITCmGdxzOJCubNFLyaU9788Ed/b+Y5sC4L2H10FFK5vpsrdEXpEgcuW+Ti7rAG9/R6XTGGZmdhEA2a7C4iiRfY4o="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
