travis:
  secure:
    BINSTAR_TOKEN: UgDOK3odqN2Xjck1uUN9rmz/erhu/CyEAKj7j4aokaEeXUTxpJi3D7axrVa/5W0yi3fgrCIG4PreJtiSVLYo4+KdEYKFifP903jrb0HvzVe6wASPS41xSb6C1ipxhpozz9Tgumi3PkdncZtD3vpAJCpwaVzMr5TTpI93eld9Ji8ebNGMrGqwaOE1E4GxM/MD0wg/p6j7IJT2tTA93XbYufdgYTSFoxkyUvjq1LnJsjclkekMWQy+L6zjvAXBaFjvPdo6D34gn4YLge8xnCceQZT0U/Te79dBPWv4Ld+gFiKIH4+ZVWifqGn9iRB9TVmWdQb6BkVMZ7AN/TpiOsxYjBQftyGimsLP20aa7s2MYHVuRoL+C44sON8Ib3KXLwFc3Na5WPleOgt/z2+tAAqaOTioDfZ+OV/cHTNkcPSDeqTLnoDRyGZfXaE6QSM28LhUEUimK2dZ54b/LV3opCKRKl9z5ejt3SQVWBjPbplwl4vmQNUDUmOoi2DmY4mnP0Ew83Tvl8dw94ZLIkVDhJ2isCV/CiY3zBUQEeGz0Z8frQwEYt6rqzheGw29pkaYYb/qgv31cq6A1+HyVlJYnu/kvfKa3le3/XQCSex3IC97w8XU+ML4RcGHnfPxUAtAITj7v00fX3yJJF3oNm4/vvGE9qlSyJAoQ2oJIxYtSH4Daws=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
