travis:
  secure:
    BINSTAR_TOKEN: lXCOk1ln7I9XORrAylxeeWWmfAqJL1IWIMXYfbJUd2u5PRA+YpMs3/XcGPozRl/xiy6KrOJY69rBRWvn5ZssbRtdEkhHV5fA/EdkQ0dlGYmRR6QMv+bhx56ld6f0ecaAtsMn9RMfcA2a+47pTwAlfVHcNs/LaPByCLW768PB2wp6KtEaAtjuEzmUPQw/3cB/24bR+D1NQqmFOAD3ntYqtiF3BWtexHLKBGh/Nx6vbE1RV3f+LdEM+ahYSVxgGSPVEy/yTobaoqfGE+IyjlxkRvNpbAnx+bXSxbmJDdP8U5iPNJZeZPnjZ9vmiY26VEGHqeMv53Zs/ZWXRrGAsXjE4TF9CRm2zwJ+eIyFHJpfkDmGSW2P3qWMSMqeLbsj2Fp6sgTpyqKssHdxSq0UamOMkTeeIbpj2jEqzyCO2JnqDsktbjERDBrddfTw6uMA2AtIn5xGtoYA6FSMsiVmHqMUJnrvGy17RpmFEHCo5B3qDfdkPlnA5/OJO9EdFrf+wfB/s9fClIarrVcrjq96EgcIKdqSXm6DWM+VpU13IIhF9+6ykv2gowiIXs4NLvvgKsGebOSjHjYekU6d/iXJ4emITCmGdxzOJCubNFLyaU9788Ed/b+Y5sC4L2H10FFK5vpsrdEXpEgcuW+Ti7rAG9/R6XTGGZmdhEA2a7C4iiRfY4o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
