travis:
  secure:
    BINSTAR_TOKEN: 6XxT5Y3m6kgwJpFlVHb6+Nhvlut71Wm5ZA7+Pyce3jkqAWldJ5OFBquhGtpLuXF2gyXY9Aicq6P28y+JQoQLwxmt9pbNnZhJqQK8tYuONZ2/ic+x04fJgW7fmxVJKVsSLHSQlcqQYz3oOhpR+kN+4sAbqgD/zodOya+PlAcvvrj0XSAgOK3CUm2A1iK0MEXUNoTolrHdvW8Tb3M5Ejy48tqDatlyNJdylF9/Bsz1UX9xE4YEG+rfuqp8Sbu5JzqKyQ3L+fc+NJwf9DeGgo0mCwg6xcM3rs7GehMDITvAd6HHtXp0IhipjixIvxXL5CVuW6Bi5Mb0EdRHJqVUD63op4cmCR9R3m0VeS+kX1aFXlb9T/W6tEDcyM+fK1a3LpGvOx7Wgi05NjRJwSwWKgk9+mcwJrHOSE/bMHwjBqHgaJLj65kXzqjKQB8V23imGD3TplIaqAhvM5GHrGbNAgbay3mMJRbXTyYzCYoBBNqG2BDH6NMJEBwYF00A39vu1QGT3NroKa0bJVzKJyqsmdc3ylKrxmWUnZHbL+iwsoc5/+72niSa02mbC0uqgOGyp4iDucabXfD6oXQBuIAjAI93RXKXRbr+IF9Fekv0MJjjqNDcK5MtwHkei5fbjAmDTn8JuidCb6rT/M1gwMj89ozpSScLvo4chSpZJel4CHcQOVA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
